# Generated by Django 4.1.1 on 2022-09-20 22:46

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prueba",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=140)),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "emisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emisorp_mensaje",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receptor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receptorp_mensaje",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        default="default.jpg", upload_to="imagenesPerfil"
                    ),
                ),
                (
                    "descripcion",
                    ckeditor.fields.RichTextField(blank=True, max_length=500),
                ),
                ("pagina_web", models.URLField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mensaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=140)),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "emisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emisor_mensaje",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receptor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receptor_mensaje",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
