# Generated by Django 4.0.6 on 2022-09-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['-fecha']},
        ),
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
