# Generated by Django 4.0.6 on 2022-09-26 00:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_perfil_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
