# Generated by Django 4.0.6 on 2022-09-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_post_options_post_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
